# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3707ebf6765eeaba7e9d0bb8d0e858146e26f591215e56a6474d49a707aaa2495808da1ec27ef18ada0080b6703234510c7a7375af1090db1adda91d4ce06a80

test:
  secret_key_base: 1f9e08a5d186857bb6c72ef8e7c6342cd1996bde29dae8d38990b704ab919fa19518b6dc1b29d991669c81741f7b7a115e1d94aef27969c12021dc0a773d398c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
